//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VFMClasses.FuelerLinxDegaIntegration {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DegaIntegrationSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseClass))]
    public partial class DegaIntegration : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTransactionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DegaIntegration() {
            this.Url = global::VFMClasses.Properties.Settings.Default.VFMClasses_FuelerLinxDegaIntegration_DegaIntegration;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTransactionCompletedEventHandler GetTransactionCompleted;
        
        /// <remarks/>
        public event UpdateTransactionCompletedEventHandler UpdateTransactionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DegaObject GetTransaction(int DegaServiceID) {
            object[] results = this.Invoke("GetTransaction", new object[] {
                        DegaServiceID});
            return ((DegaObject)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransactionAsync(int DegaServiceID) {
            this.GetTransactionAsync(DegaServiceID, null);
        }
        
        /// <remarks/>
        public void GetTransactionAsync(int DegaServiceID, object userState) {
            if ((this.GetTransactionOperationCompleted == null)) {
                this.GetTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionOperationCompleted);
            }
            this.InvokeAsync("GetTransaction", new object[] {
                        DegaServiceID}, this.GetTransactionOperationCompleted, userState);
        }
        
        private void OnGetTransactionOperationCompleted(object arg) {
            if ((this.GetTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransactionCompleted(this, new GetTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateTransaction(DegaObject transaction) {
            object[] results = this.Invoke("UpdateTransaction", new object[] {
                        transaction});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTransactionAsync(DegaObject transaction) {
            this.UpdateTransactionAsync(transaction, null);
        }
        
        /// <remarks/>
        public void UpdateTransactionAsync(DegaObject transaction, object userState) {
            if ((this.UpdateTransactionOperationCompleted == null)) {
                this.UpdateTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTransactionOperationCompleted);
            }
            this.InvokeAsync("UpdateTransaction", new object[] {
                        transaction}, this.UpdateTransactionOperationCompleted, userState);
        }
        
        private void OnUpdateTransactionOperationCompleted(object arg) {
            if ((this.UpdateTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTransactionCompleted(this, new UpdateTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DegaObject : Transaction {
        
        private System.Guid accountIdField;
        
        private int idField;
        
        private string tailNumberField;
        
        private System.DateTime dateRequestedField;
        
        private AdminStatuses adminStatusField;
        
        private CustStatuses custStatusField;
        
        private decimal quotedPPGField;
        
        private System.DateTime fuelingDateTimeField;
        
        private string processNameField;
        
        private InvoiceStatuses degaInvoiceStatusField;
        
        private string certificateTypeField;
        
        private string fuelOnField;
        
        private decimal invoicedPPGField;
        
        private decimal invoicedVolumeField;
        
        private double basePPGField;
        
        private double postedRetailField;
        
        private string adminNotesField;
        
        private double rampFeeField;
        
        private double rampFeeWaivedAtField;
        
        private string invoiceNumberField;
        
        private bool noFuelField;
        
        private string requestedByField;
        
        /// <remarks/>
        public System.Guid AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string TailNumber {
            get {
                return this.tailNumberField;
            }
            set {
                this.tailNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateRequested {
            get {
                return this.dateRequestedField;
            }
            set {
                this.dateRequestedField = value;
            }
        }
        
        /// <remarks/>
        public AdminStatuses AdminStatus {
            get {
                return this.adminStatusField;
            }
            set {
                this.adminStatusField = value;
            }
        }
        
        /// <remarks/>
        public CustStatuses CustStatus {
            get {
                return this.custStatusField;
            }
            set {
                this.custStatusField = value;
            }
        }
        
        /// <remarks/>
        public decimal QuotedPPG {
            get {
                return this.quotedPPGField;
            }
            set {
                this.quotedPPGField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FuelingDateTime {
            get {
                return this.fuelingDateTimeField;
            }
            set {
                this.fuelingDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessName {
            get {
                return this.processNameField;
            }
            set {
                this.processNameField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceStatuses DegaInvoiceStatus {
            get {
                return this.degaInvoiceStatusField;
            }
            set {
                this.degaInvoiceStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CertificateType {
            get {
                return this.certificateTypeField;
            }
            set {
                this.certificateTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FuelOn {
            get {
                return this.fuelOnField;
            }
            set {
                this.fuelOnField = value;
            }
        }
        
        /// <remarks/>
        public decimal InvoicedPPG {
            get {
                return this.invoicedPPGField;
            }
            set {
                this.invoicedPPGField = value;
            }
        }
        
        /// <remarks/>
        public decimal InvoicedVolume {
            get {
                return this.invoicedVolumeField;
            }
            set {
                this.invoicedVolumeField = value;
            }
        }
        
        /// <remarks/>
        public double BasePPG {
            get {
                return this.basePPGField;
            }
            set {
                this.basePPGField = value;
            }
        }
        
        /// <remarks/>
        public double PostedRetail {
            get {
                return this.postedRetailField;
            }
            set {
                this.postedRetailField = value;
            }
        }
        
        /// <remarks/>
        public string AdminNotes {
            get {
                return this.adminNotesField;
            }
            set {
                this.adminNotesField = value;
            }
        }
        
        /// <remarks/>
        public double RampFee {
            get {
                return this.rampFeeField;
            }
            set {
                this.rampFeeField = value;
            }
        }
        
        /// <remarks/>
        public double RampFeeWaivedAt {
            get {
                return this.rampFeeWaivedAtField;
            }
            set {
                this.rampFeeWaivedAtField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool NoFuel {
            get {
                return this.noFuelField;
            }
            set {
                this.noFuelField = value;
            }
        }
        
        /// <remarks/>
        public string RequestedBy {
            get {
                return this.requestedByField;
            }
            set {
                this.requestedByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum AdminStatuses {
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        FboNotified,
        
        /// <remarks/>
        Confirmed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum CustStatuses {
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Reconciled,
        
        /// <remarks/>
        Discrepancy,
        
        /// <remarks/>
        Cancelled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum InvoiceStatuses {
        
        /// <remarks/>
        NotSpecified,
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Modify,
        
        /// <remarks/>
        PostVerify,
        
        /// <remarks/>
        MarginAnalysis,
        
        /// <remarks/>
        Discrepancy,
        
        /// <remarks/>
        Accounting,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Reconciled,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        NoFuel,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DegaObject))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Transaction : BaseClass {
        
        private int oIDField;
        
        private int member_idField;
        
        private int airportIDField;
        
        private string fBOField;
        
        private int fuelerIDField;
        
        private int userAircraftIDField;
        
        private bool reconciledField;
        
        private bool discrepancyField;
        
        private bool cancelledField;
        
        private string tail_numberField;
        
        private System.DateTime etaField;
        
        private System.DateTime etdField;
        
        private string iCAOField;
        
        private string iATAField;
        
        private string fuel_relationship_1Field;
        
        private double fuel_est_weightField;
        
        private double fuel_est_costField;
        
        private string fbo_notesField;
        
        private System.DateTime creation_dateField;
        
        private TimePreferences time_standardField;
        
        private double invoicedWholesaleField;
        
        private double actualPPGField;
        
        private double actualVolumeField;
        
        private double basePPGField;
        
        private double postedRetailField;
        
        private double plattsPriceField;
        
        private int tripIDField;
        
        private int integrationTripIDField;
        
        private bool forcedReconcileField;
        
        private bool archivedField;
        
        private int companyIDField;
        
        private string fuelerField;
        
        private int webDispatchIDField;
        
        private bool directField;
        
        private int memoForField;
        
        private bool discCorrectedField;
        
        private bool customNotesField;
        
        private FuelReqFees reqFeesField;
        
        private TransactionFuelPrice[] transactionFuelPriceCollectionField;
        
        private otherFee[] otherFeesField;
        
        private otherTax[] otherTaxesField;
        
        private double quotedRetailOriginalField;
        
        private Integration integrationInfoField;
        
        private string invoiceStatusField;
        
        private LegSettings legSettingsField;
        
        private double oldfuel_est_costField;
        
        private int fuelMasterIDField;
        
        private TransactionDetails transactionDetailsField;
        
        private bool isFromDegaField;
        
        /// <remarks/>
        public int OID {
            get {
                return this.oIDField;
            }
            set {
                this.oIDField = value;
            }
        }
        
        /// <remarks/>
        public int member_id {
            get {
                return this.member_idField;
            }
            set {
                this.member_idField = value;
            }
        }
        
        /// <remarks/>
        public int AirportID {
            get {
                return this.airportIDField;
            }
            set {
                this.airportIDField = value;
            }
        }
        
        /// <remarks/>
        public string FBO {
            get {
                return this.fBOField;
            }
            set {
                this.fBOField = value;
            }
        }
        
        /// <remarks/>
        public int FuelerID {
            get {
                return this.fuelerIDField;
            }
            set {
                this.fuelerIDField = value;
            }
        }
        
        /// <remarks/>
        public int UserAircraftID {
            get {
                return this.userAircraftIDField;
            }
            set {
                this.userAircraftIDField = value;
            }
        }
        
        /// <remarks/>
        public bool reconciled {
            get {
                return this.reconciledField;
            }
            set {
                this.reconciledField = value;
            }
        }
        
        /// <remarks/>
        public bool discrepancy {
            get {
                return this.discrepancyField;
            }
            set {
                this.discrepancyField = value;
            }
        }
        
        /// <remarks/>
        public bool cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
            }
        }
        
        /// <remarks/>
        public string tail_number {
            get {
                return this.tail_numberField;
            }
            set {
                this.tail_numberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime eta {
            get {
                return this.etaField;
            }
            set {
                this.etaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime etd {
            get {
                return this.etdField;
            }
            set {
                this.etdField = value;
            }
        }
        
        /// <remarks/>
        public string ICAO {
            get {
                return this.iCAOField;
            }
            set {
                this.iCAOField = value;
            }
        }
        
        /// <remarks/>
        public string IATA {
            get {
                return this.iATAField;
            }
            set {
                this.iATAField = value;
            }
        }
        
        /// <remarks/>
        public string fuel_relationship_1 {
            get {
                return this.fuel_relationship_1Field;
            }
            set {
                this.fuel_relationship_1Field = value;
            }
        }
        
        /// <remarks/>
        public double fuel_est_weight {
            get {
                return this.fuel_est_weightField;
            }
            set {
                this.fuel_est_weightField = value;
            }
        }
        
        /// <remarks/>
        public double fuel_est_cost {
            get {
                return this.fuel_est_costField;
            }
            set {
                this.fuel_est_costField = value;
            }
        }
        
        /// <remarks/>
        public string fbo_notes {
            get {
                return this.fbo_notesField;
            }
            set {
                this.fbo_notesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime creation_date {
            get {
                return this.creation_dateField;
            }
            set {
                this.creation_dateField = value;
            }
        }
        
        /// <remarks/>
        public TimePreferences time_standard {
            get {
                return this.time_standardField;
            }
            set {
                this.time_standardField = value;
            }
        }
        
        /// <remarks/>
        public double invoicedWholesale {
            get {
                return this.invoicedWholesaleField;
            }
            set {
                this.invoicedWholesaleField = value;
            }
        }
        
        /// <remarks/>
        public double ActualPPG {
            get {
                return this.actualPPGField;
            }
            set {
                this.actualPPGField = value;
            }
        }
        
        /// <remarks/>
        public double ActualVolume {
            get {
                return this.actualVolumeField;
            }
            set {
                this.actualVolumeField = value;
            }
        }
        
        /// <remarks/>
        public double basePPG {
            get {
                return this.basePPGField;
            }
            set {
                this.basePPGField = value;
            }
        }
        
        /// <remarks/>
        public double postedRetail {
            get {
                return this.postedRetailField;
            }
            set {
                this.postedRetailField = value;
            }
        }
        
        /// <remarks/>
        public double PlattsPrice {
            get {
                return this.plattsPriceField;
            }
            set {
                this.plattsPriceField = value;
            }
        }
        
        /// <remarks/>
        public int TripID {
            get {
                return this.tripIDField;
            }
            set {
                this.tripIDField = value;
            }
        }
        
        /// <remarks/>
        public int IntegrationTripID {
            get {
                return this.integrationTripIDField;
            }
            set {
                this.integrationTripIDField = value;
            }
        }
        
        /// <remarks/>
        public bool forcedReconcile {
            get {
                return this.forcedReconcileField;
            }
            set {
                this.forcedReconcileField = value;
            }
        }
        
        /// <remarks/>
        public bool archived {
            get {
                return this.archivedField;
            }
            set {
                this.archivedField = value;
            }
        }
        
        /// <remarks/>
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        public string Fueler {
            get {
                return this.fuelerField;
            }
            set {
                this.fuelerField = value;
            }
        }
        
        /// <remarks/>
        public int WebDispatchID {
            get {
                return this.webDispatchIDField;
            }
            set {
                this.webDispatchIDField = value;
            }
        }
        
        /// <remarks/>
        public bool Direct {
            get {
                return this.directField;
            }
            set {
                this.directField = value;
            }
        }
        
        /// <remarks/>
        public int MemoFor {
            get {
                return this.memoForField;
            }
            set {
                this.memoForField = value;
            }
        }
        
        /// <remarks/>
        public bool DiscCorrected {
            get {
                return this.discCorrectedField;
            }
            set {
                this.discCorrectedField = value;
            }
        }
        
        /// <remarks/>
        public bool CustomNotes {
            get {
                return this.customNotesField;
            }
            set {
                this.customNotesField = value;
            }
        }
        
        /// <remarks/>
        public FuelReqFees ReqFees {
            get {
                return this.reqFeesField;
            }
            set {
                this.reqFeesField = value;
            }
        }
        
        /// <remarks/>
        public TransactionFuelPrice[] TransactionFuelPriceCollection {
            get {
                return this.transactionFuelPriceCollectionField;
            }
            set {
                this.transactionFuelPriceCollectionField = value;
            }
        }
        
        /// <remarks/>
        public otherFee[] OtherFees {
            get {
                return this.otherFeesField;
            }
            set {
                this.otherFeesField = value;
            }
        }
        
        /// <remarks/>
        public otherTax[] OtherTaxes {
            get {
                return this.otherTaxesField;
            }
            set {
                this.otherTaxesField = value;
            }
        }
        
        /// <remarks/>
        public double QuotedRetailOriginal {
            get {
                return this.quotedRetailOriginalField;
            }
            set {
                this.quotedRetailOriginalField = value;
            }
        }
        
        /// <remarks/>
        public Integration IntegrationInfo {
            get {
                return this.integrationInfoField;
            }
            set {
                this.integrationInfoField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceStatus {
            get {
                return this.invoiceStatusField;
            }
            set {
                this.invoiceStatusField = value;
            }
        }
        
        /// <remarks/>
        public LegSettings LegSettings {
            get {
                return this.legSettingsField;
            }
            set {
                this.legSettingsField = value;
            }
        }
        
        /// <remarks/>
        public double Oldfuel_est_cost {
            get {
                return this.oldfuel_est_costField;
            }
            set {
                this.oldfuel_est_costField = value;
            }
        }
        
        /// <remarks/>
        public int FuelMasterID {
            get {
                return this.fuelMasterIDField;
            }
            set {
                this.fuelMasterIDField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetails TransactionDetails {
            get {
                return this.transactionDetailsField;
            }
            set {
                this.transactionDetailsField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFromDega {
            get {
                return this.isFromDegaField;
            }
            set {
                this.isFromDegaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TimePreferences {
        
        /// <remarks/>
        Z,
        
        /// <remarks/>
        L,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FuelReqFees : BaseClass {
        
        private long oidField;
        
        private int requestIdField;
        
        private int memberIdField;
        
        private double fedTaxField;
        
        private double stateTaxField;
        
        private double salesTaxField;
        
        private double totalExpensesField;
        
        private string dispatchNumberField;
        
        private string invoiceNumberField;
        
        private double passengerLoadField;
        
        private double cateringChargeFeeField;
        
        private double lAVServiceFeeField;
        
        private double rampFeeField;
        
        private double iTPFeeField;
        
        private int loadTypeField;
        
        private double vatField;
        
        private double motField;
        
        private double flowFeeField;
        
        private double otherFeesField;
        
        private double miscTaxField;
        
        private double additiveField;
        
        private double gPUAPUFeeField;
        
        private double potableWaterFeeField;
        
        private double landingFeeField;
        
        private string taxesOmitField;
        
        private double retailTotalField;
        
        private double oilSpillFeeField;
        
        private double stateOilSpillFeeField;
        
        private string fuelerInvoiceNumberField;
        
        private bool rampFeeWaivedField;
        
        private double rampFeeWaivedAtField;
        
        private int processIDField;
        
        private bool rampFeeCallFBOField;
        
        private double reportedRampFeeField;
        
        /// <remarks/>
        public long Oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
            }
        }
        
        /// <remarks/>
        public int RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        public int MemberId {
            get {
                return this.memberIdField;
            }
            set {
                this.memberIdField = value;
            }
        }
        
        /// <remarks/>
        public double FedTax {
            get {
                return this.fedTaxField;
            }
            set {
                this.fedTaxField = value;
            }
        }
        
        /// <remarks/>
        public double StateTax {
            get {
                return this.stateTaxField;
            }
            set {
                this.stateTaxField = value;
            }
        }
        
        /// <remarks/>
        public double SalesTax {
            get {
                return this.salesTaxField;
            }
            set {
                this.salesTaxField = value;
            }
        }
        
        /// <remarks/>
        public double TotalExpenses {
            get {
                return this.totalExpensesField;
            }
            set {
                this.totalExpensesField = value;
            }
        }
        
        /// <remarks/>
        public string DispatchNumber {
            get {
                return this.dispatchNumberField;
            }
            set {
                this.dispatchNumberField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public double PassengerLoad {
            get {
                return this.passengerLoadField;
            }
            set {
                this.passengerLoadField = value;
            }
        }
        
        /// <remarks/>
        public double CateringChargeFee {
            get {
                return this.cateringChargeFeeField;
            }
            set {
                this.cateringChargeFeeField = value;
            }
        }
        
        /// <remarks/>
        public double LAVServiceFee {
            get {
                return this.lAVServiceFeeField;
            }
            set {
                this.lAVServiceFeeField = value;
            }
        }
        
        /// <remarks/>
        public double RampFee {
            get {
                return this.rampFeeField;
            }
            set {
                this.rampFeeField = value;
            }
        }
        
        /// <remarks/>
        public double ITPFee {
            get {
                return this.iTPFeeField;
            }
            set {
                this.iTPFeeField = value;
            }
        }
        
        /// <remarks/>
        public int LoadType {
            get {
                return this.loadTypeField;
            }
            set {
                this.loadTypeField = value;
            }
        }
        
        /// <remarks/>
        public double Vat {
            get {
                return this.vatField;
            }
            set {
                this.vatField = value;
            }
        }
        
        /// <remarks/>
        public double Mot {
            get {
                return this.motField;
            }
            set {
                this.motField = value;
            }
        }
        
        /// <remarks/>
        public double FlowFee {
            get {
                return this.flowFeeField;
            }
            set {
                this.flowFeeField = value;
            }
        }
        
        /// <remarks/>
        public double OtherFees {
            get {
                return this.otherFeesField;
            }
            set {
                this.otherFeesField = value;
            }
        }
        
        /// <remarks/>
        public double MiscTax {
            get {
                return this.miscTaxField;
            }
            set {
                this.miscTaxField = value;
            }
        }
        
        /// <remarks/>
        public double Additive {
            get {
                return this.additiveField;
            }
            set {
                this.additiveField = value;
            }
        }
        
        /// <remarks/>
        public double GPUAPUFee {
            get {
                return this.gPUAPUFeeField;
            }
            set {
                this.gPUAPUFeeField = value;
            }
        }
        
        /// <remarks/>
        public double PotableWaterFee {
            get {
                return this.potableWaterFeeField;
            }
            set {
                this.potableWaterFeeField = value;
            }
        }
        
        /// <remarks/>
        public double LandingFee {
            get {
                return this.landingFeeField;
            }
            set {
                this.landingFeeField = value;
            }
        }
        
        /// <remarks/>
        public string TaxesOmit {
            get {
                return this.taxesOmitField;
            }
            set {
                this.taxesOmitField = value;
            }
        }
        
        /// <remarks/>
        public double RetailTotal {
            get {
                return this.retailTotalField;
            }
            set {
                this.retailTotalField = value;
            }
        }
        
        /// <remarks/>
        public double OilSpillFee {
            get {
                return this.oilSpillFeeField;
            }
            set {
                this.oilSpillFeeField = value;
            }
        }
        
        /// <remarks/>
        public double StateOilSpillFee {
            get {
                return this.stateOilSpillFeeField;
            }
            set {
                this.stateOilSpillFeeField = value;
            }
        }
        
        /// <remarks/>
        public string FuelerInvoiceNumber {
            get {
                return this.fuelerInvoiceNumberField;
            }
            set {
                this.fuelerInvoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool RampFeeWaived {
            get {
                return this.rampFeeWaivedField;
            }
            set {
                this.rampFeeWaivedField = value;
            }
        }
        
        /// <remarks/>
        public double RampFeeWaivedAt {
            get {
                return this.rampFeeWaivedAtField;
            }
            set {
                this.rampFeeWaivedAtField = value;
            }
        }
        
        /// <remarks/>
        public int ProcessID {
            get {
                return this.processIDField;
            }
            set {
                this.processIDField = value;
            }
        }
        
        /// <remarks/>
        public bool RampFeeCallFBO {
            get {
                return this.rampFeeCallFBOField;
            }
            set {
                this.rampFeeCallFBOField = value;
            }
        }
        
        /// <remarks/>
        public double ReportedRampFee {
            get {
                return this.reportedRampFeeField;
            }
            set {
                this.reportedRampFeeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactionDetails))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxBreakdown))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FilterableTax))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LegSettings))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Integration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(otherTax))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(otherFee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactionFuelPrice))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FuelReqFees))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Transaction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DegaObject))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseClass {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransactionDetails : BaseClass {
        
        private string flightTypeField;
        
        private string schedulingServiceIDField;
        
        private string fuelOnField;
        
        private bool noFuelField;
        
        private bool divertedField;
        
        private TaxStorageTypes taxStorageTypeField;
        
        private TaxStatuses taxStatusField;
        
        private int degaServiceIDField;
        
        /// <remarks/>
        public string FlightType {
            get {
                return this.flightTypeField;
            }
            set {
                this.flightTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SchedulingServiceID {
            get {
                return this.schedulingServiceIDField;
            }
            set {
                this.schedulingServiceIDField = value;
            }
        }
        
        /// <remarks/>
        public string FuelOn {
            get {
                return this.fuelOnField;
            }
            set {
                this.fuelOnField = value;
            }
        }
        
        /// <remarks/>
        public bool NoFuel {
            get {
                return this.noFuelField;
            }
            set {
                this.noFuelField = value;
            }
        }
        
        /// <remarks/>
        public bool Diverted {
            get {
                return this.divertedField;
            }
            set {
                this.divertedField = value;
            }
        }
        
        /// <remarks/>
        public TaxStorageTypes TaxStorageType {
            get {
                return this.taxStorageTypeField;
            }
            set {
                this.taxStorageTypeField = value;
            }
        }
        
        /// <remarks/>
        public TaxStatuses TaxStatus {
            get {
                return this.taxStatusField;
            }
            set {
                this.taxStatusField = value;
            }
        }
        
        /// <remarks/>
        public int DegaServiceID {
            get {
                return this.degaServiceIDField;
            }
            set {
                this.degaServiceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TaxStorageTypes {
        
        /// <remarks/>
        PPG,
        
        /// <remarks/>
        Flat,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TaxStatuses {
        
        /// <remarks/>
        Unstarted,
        
        /// <remarks/>
        InProcess,
        
        /// <remarks/>
        Completed,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FilterableTax))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TaxBreakdown : BaseClass {
        
        private int fuelMasterIDField;
        
        private double minVolumeField;
        
        private double maxVolumeField;
        
        private string descriptionField;
        
        private double priceField;
        
        private string currencyField;
        
        private string unitOfMeasureField;
        
        private bool isEstimatedByCBVatField;
        
        private double percentagePriceOfBaseField;
        
        /// <remarks/>
        public int FuelMasterID {
            get {
                return this.fuelMasterIDField;
            }
            set {
                this.fuelMasterIDField = value;
            }
        }
        
        /// <remarks/>
        public double MinVolume {
            get {
                return this.minVolumeField;
            }
            set {
                this.minVolumeField = value;
            }
        }
        
        /// <remarks/>
        public double MaxVolume {
            get {
                return this.maxVolumeField;
            }
            set {
                this.maxVolumeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string UnitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEstimatedByCBVat {
            get {
                return this.isEstimatedByCBVatField;
            }
            set {
                this.isEstimatedByCBVatField = value;
            }
        }
        
        /// <remarks/>
        public double PercentagePriceOfBase {
            get {
                return this.percentagePriceOfBaseField;
            }
            set {
                this.percentagePriceOfBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FilterableTax : TaxBreakdown {
        
        private bool isFilteredField;
        
        /// <remarks/>
        public bool IsFiltered {
            get {
                return this.isFilteredField;
            }
            set {
                this.isFilteredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LegSettings : BaseClass {
        
        private double minReserveField;
        
        private double maxLandingWeightField;
        
        private double maxTakeoffWeightField;
        
        private double basicOperatingWeightField;
        
        private bool areWeightsChangedField;
        
        private int flightLevelField;
        
        private int maxFlightLevelField;
        
        private int numberOfPassengersField;
        
        private double cargoWeightInPoundsField;
        
        private double passengerWeightInPoundsField;
        
        private bool useDirectRouteField;
        
        private bool isETOPSFlightField;
        
        private FilterableTax[] filterableTaxCollectionField;
        
        private double fuelBiasField;
        
        private double speedBiasField;
        
        private string alternateAirportField;
        
        private string flightTypeField;
        
        private string nextDestinationField;
        
        private bool landWithMaxFuelField;
        
        private bool useFlightDataField;
        
        private bool lockFuelAmountField;
        
        private string handlerNameField;
        
        private string handlerEmailField;
        
        private int requestIDField;
        
        private double minExtraReserveField;
        
        /// <remarks/>
        public double MinReserve {
            get {
                return this.minReserveField;
            }
            set {
                this.minReserveField = value;
            }
        }
        
        /// <remarks/>
        public double MaxLandingWeight {
            get {
                return this.maxLandingWeightField;
            }
            set {
                this.maxLandingWeightField = value;
            }
        }
        
        /// <remarks/>
        public double MaxTakeoffWeight {
            get {
                return this.maxTakeoffWeightField;
            }
            set {
                this.maxTakeoffWeightField = value;
            }
        }
        
        /// <remarks/>
        public double BasicOperatingWeight {
            get {
                return this.basicOperatingWeightField;
            }
            set {
                this.basicOperatingWeightField = value;
            }
        }
        
        /// <remarks/>
        public bool AreWeightsChanged {
            get {
                return this.areWeightsChangedField;
            }
            set {
                this.areWeightsChangedField = value;
            }
        }
        
        /// <remarks/>
        public int FlightLevel {
            get {
                return this.flightLevelField;
            }
            set {
                this.flightLevelField = value;
            }
        }
        
        /// <remarks/>
        public int MaxFlightLevel {
            get {
                return this.maxFlightLevelField;
            }
            set {
                this.maxFlightLevelField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfPassengers {
            get {
                return this.numberOfPassengersField;
            }
            set {
                this.numberOfPassengersField = value;
            }
        }
        
        /// <remarks/>
        public double CargoWeightInPounds {
            get {
                return this.cargoWeightInPoundsField;
            }
            set {
                this.cargoWeightInPoundsField = value;
            }
        }
        
        /// <remarks/>
        public double PassengerWeightInPounds {
            get {
                return this.passengerWeightInPoundsField;
            }
            set {
                this.passengerWeightInPoundsField = value;
            }
        }
        
        /// <remarks/>
        public bool UseDirectRoute {
            get {
                return this.useDirectRouteField;
            }
            set {
                this.useDirectRouteField = value;
            }
        }
        
        /// <remarks/>
        public bool IsETOPSFlight {
            get {
                return this.isETOPSFlightField;
            }
            set {
                this.isETOPSFlightField = value;
            }
        }
        
        /// <remarks/>
        public FilterableTax[] FilterableTaxCollection {
            get {
                return this.filterableTaxCollectionField;
            }
            set {
                this.filterableTaxCollectionField = value;
            }
        }
        
        /// <remarks/>
        public double FuelBias {
            get {
                return this.fuelBiasField;
            }
            set {
                this.fuelBiasField = value;
            }
        }
        
        /// <remarks/>
        public double SpeedBias {
            get {
                return this.speedBiasField;
            }
            set {
                this.speedBiasField = value;
            }
        }
        
        /// <remarks/>
        public string AlternateAirport {
            get {
                return this.alternateAirportField;
            }
            set {
                this.alternateAirportField = value;
            }
        }
        
        /// <remarks/>
        public string FlightType {
            get {
                return this.flightTypeField;
            }
            set {
                this.flightTypeField = value;
            }
        }
        
        /// <remarks/>
        public string NextDestination {
            get {
                return this.nextDestinationField;
            }
            set {
                this.nextDestinationField = value;
            }
        }
        
        /// <remarks/>
        public bool LandWithMaxFuel {
            get {
                return this.landWithMaxFuelField;
            }
            set {
                this.landWithMaxFuelField = value;
            }
        }
        
        /// <remarks/>
        public bool UseFlightData {
            get {
                return this.useFlightDataField;
            }
            set {
                this.useFlightDataField = value;
            }
        }
        
        /// <remarks/>
        public bool LockFuelAmount {
            get {
                return this.lockFuelAmountField;
            }
            set {
                this.lockFuelAmountField = value;
            }
        }
        
        /// <remarks/>
        public string HandlerName {
            get {
                return this.handlerNameField;
            }
            set {
                this.handlerNameField = value;
            }
        }
        
        /// <remarks/>
        public string HandlerEmail {
            get {
                return this.handlerEmailField;
            }
            set {
                this.handlerEmailField = value;
            }
        }
        
        /// <remarks/>
        public int RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public double MinExtraReserve {
            get {
                return this.minExtraReserveField;
            }
            set {
                this.minExtraReserveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Integration : BaseClass {
        
        private int oIDField;
        
        private int memberIDField;
        
        private int processIDField;
        
        private FPIntegrations integrationTypeField;
        
        private string tripsAircraftIDField;
        
        private int tripsTripNumberField;
        
        private int legsKIDdateField;
        
        private int legsKIDtimeField;
        
        private string legsKIDuserField;
        
        private int legsKIDmultField;
        
        private int legsKIDcommField;
        
        private bool tripsTripStatusClosedField;
        
        private string tripsAircraftTypeIDField;
        
        private int tripsDepartDateZuluField;
        
        private string tripsAircraftTailNumberField;
        
        private string legsAircraftIDField;
        
        private string arrivalICAOField;
        
        private int eTDZuluField;
        
        private int eTAZuluField;
        
        private int departDateZULUField;
        
        private int arriveDateZuluField;
        
        private int eTDLocalField;
        
        private int eTALocalField;
        
        private int departDateLocalField;
        
        private int arriveDateLocalField;
        
        private int legNumberField;
        
        private int fuelburnField;
        
        private string departICAOField;
        
        private int statusField;
        
        private bool cancelledField;
        
        private int cancelCodeField;
        
        private string preferFBOField;
        
        private int arrivalRequestIDField;
        
        private int departureRequestIDField;
        
        private bool viewedField;
        
        private string arrivalPrefFBOField;
        
        private string departurePrefFBOField;
        
        private string fOSCustomerNameField;
        
        private string tripTypeField;
        
        private int cargoLbsField;
        
        private int mTOWField;
        
        private int paxCountField;
        
        private int windField;
        
        private int tASField;
        
        private int altitudeField;
        
        private int fuelOutField;
        
        private int fuelInField;
        
        private int femalePaxCountField;
        
        private int malePaxCountField;
        
        /// <remarks/>
        public int OID {
            get {
                return this.oIDField;
            }
            set {
                this.oIDField = value;
            }
        }
        
        /// <remarks/>
        public int MemberID {
            get {
                return this.memberIDField;
            }
            set {
                this.memberIDField = value;
            }
        }
        
        /// <remarks/>
        public int ProcessID {
            get {
                return this.processIDField;
            }
            set {
                this.processIDField = value;
            }
        }
        
        /// <remarks/>
        public FPIntegrations IntegrationType {
            get {
                return this.integrationTypeField;
            }
            set {
                this.integrationTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TripsAircraftID {
            get {
                return this.tripsAircraftIDField;
            }
            set {
                this.tripsAircraftIDField = value;
            }
        }
        
        /// <remarks/>
        public int TripsTripNumber {
            get {
                return this.tripsTripNumberField;
            }
            set {
                this.tripsTripNumberField = value;
            }
        }
        
        /// <remarks/>
        public int LegsKIDdate {
            get {
                return this.legsKIDdateField;
            }
            set {
                this.legsKIDdateField = value;
            }
        }
        
        /// <remarks/>
        public int LegsKIDtime {
            get {
                return this.legsKIDtimeField;
            }
            set {
                this.legsKIDtimeField = value;
            }
        }
        
        /// <remarks/>
        public string LegsKIDuser {
            get {
                return this.legsKIDuserField;
            }
            set {
                this.legsKIDuserField = value;
            }
        }
        
        /// <remarks/>
        public int LegsKIDmult {
            get {
                return this.legsKIDmultField;
            }
            set {
                this.legsKIDmultField = value;
            }
        }
        
        /// <remarks/>
        public int LegsKIDcomm {
            get {
                return this.legsKIDcommField;
            }
            set {
                this.legsKIDcommField = value;
            }
        }
        
        /// <remarks/>
        public bool TripsTripStatusClosed {
            get {
                return this.tripsTripStatusClosedField;
            }
            set {
                this.tripsTripStatusClosedField = value;
            }
        }
        
        /// <remarks/>
        public string TripsAircraftTypeID {
            get {
                return this.tripsAircraftTypeIDField;
            }
            set {
                this.tripsAircraftTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public int TripsDepartDateZulu {
            get {
                return this.tripsDepartDateZuluField;
            }
            set {
                this.tripsDepartDateZuluField = value;
            }
        }
        
        /// <remarks/>
        public string TripsAircraftTailNumber {
            get {
                return this.tripsAircraftTailNumberField;
            }
            set {
                this.tripsAircraftTailNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LegsAircraftID {
            get {
                return this.legsAircraftIDField;
            }
            set {
                this.legsAircraftIDField = value;
            }
        }
        
        /// <remarks/>
        public string ArrivalICAO {
            get {
                return this.arrivalICAOField;
            }
            set {
                this.arrivalICAOField = value;
            }
        }
        
        /// <remarks/>
        public int ETDZulu {
            get {
                return this.eTDZuluField;
            }
            set {
                this.eTDZuluField = value;
            }
        }
        
        /// <remarks/>
        public int ETAZulu {
            get {
                return this.eTAZuluField;
            }
            set {
                this.eTAZuluField = value;
            }
        }
        
        /// <remarks/>
        public int DepartDateZULU {
            get {
                return this.departDateZULUField;
            }
            set {
                this.departDateZULUField = value;
            }
        }
        
        /// <remarks/>
        public int ArriveDateZulu {
            get {
                return this.arriveDateZuluField;
            }
            set {
                this.arriveDateZuluField = value;
            }
        }
        
        /// <remarks/>
        public int ETDLocal {
            get {
                return this.eTDLocalField;
            }
            set {
                this.eTDLocalField = value;
            }
        }
        
        /// <remarks/>
        public int ETALocal {
            get {
                return this.eTALocalField;
            }
            set {
                this.eTALocalField = value;
            }
        }
        
        /// <remarks/>
        public int DepartDateLocal {
            get {
                return this.departDateLocalField;
            }
            set {
                this.departDateLocalField = value;
            }
        }
        
        /// <remarks/>
        public int ArriveDateLocal {
            get {
                return this.arriveDateLocalField;
            }
            set {
                this.arriveDateLocalField = value;
            }
        }
        
        /// <remarks/>
        public int LegNumber {
            get {
                return this.legNumberField;
            }
            set {
                this.legNumberField = value;
            }
        }
        
        /// <remarks/>
        public int Fuelburn {
            get {
                return this.fuelburnField;
            }
            set {
                this.fuelburnField = value;
            }
        }
        
        /// <remarks/>
        public string DepartICAO {
            get {
                return this.departICAOField;
            }
            set {
                this.departICAOField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public bool Cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
            }
        }
        
        /// <remarks/>
        public int CancelCode {
            get {
                return this.cancelCodeField;
            }
            set {
                this.cancelCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PreferFBO {
            get {
                return this.preferFBOField;
            }
            set {
                this.preferFBOField = value;
            }
        }
        
        /// <remarks/>
        public int ArrivalRequestID {
            get {
                return this.arrivalRequestIDField;
            }
            set {
                this.arrivalRequestIDField = value;
            }
        }
        
        /// <remarks/>
        public int DepartureRequestID {
            get {
                return this.departureRequestIDField;
            }
            set {
                this.departureRequestIDField = value;
            }
        }
        
        /// <remarks/>
        public bool Viewed {
            get {
                return this.viewedField;
            }
            set {
                this.viewedField = value;
            }
        }
        
        /// <remarks/>
        public string ArrivalPrefFBO {
            get {
                return this.arrivalPrefFBOField;
            }
            set {
                this.arrivalPrefFBOField = value;
            }
        }
        
        /// <remarks/>
        public string DeparturePrefFBO {
            get {
                return this.departurePrefFBOField;
            }
            set {
                this.departurePrefFBOField = value;
            }
        }
        
        /// <remarks/>
        public string FOSCustomerName {
            get {
                return this.fOSCustomerNameField;
            }
            set {
                this.fOSCustomerNameField = value;
            }
        }
        
        /// <remarks/>
        public string TripType {
            get {
                return this.tripTypeField;
            }
            set {
                this.tripTypeField = value;
            }
        }
        
        /// <remarks/>
        public int CargoLbs {
            get {
                return this.cargoLbsField;
            }
            set {
                this.cargoLbsField = value;
            }
        }
        
        /// <remarks/>
        public int MTOW {
            get {
                return this.mTOWField;
            }
            set {
                this.mTOWField = value;
            }
        }
        
        /// <remarks/>
        public int PaxCount {
            get {
                return this.paxCountField;
            }
            set {
                this.paxCountField = value;
            }
        }
        
        /// <remarks/>
        public int Wind {
            get {
                return this.windField;
            }
            set {
                this.windField = value;
            }
        }
        
        /// <remarks/>
        public int TAS {
            get {
                return this.tASField;
            }
            set {
                this.tASField = value;
            }
        }
        
        /// <remarks/>
        public int Altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        public int FuelOut {
            get {
                return this.fuelOutField;
            }
            set {
                this.fuelOutField = value;
            }
        }
        
        /// <remarks/>
        public int FuelIn {
            get {
                return this.fuelInField;
            }
            set {
                this.fuelInField = value;
            }
        }
        
        /// <remarks/>
        public int FemalePaxCount {
            get {
                return this.femalePaxCountField;
            }
            set {
                this.femalePaxCountField = value;
            }
        }
        
        /// <remarks/>
        public int MalePaxCount {
            get {
                return this.malePaxCountField;
            }
            set {
                this.malePaxCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum FPIntegrations {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        FOS,
        
        /// <remarks/>
        BART,
        
        /// <remarks/>
        FlightTrak,
        
        /// <remarks/>
        Avinode,
        
        /// <remarks/>
        IPC,
        
        /// <remarks/>
        FOSFlightApps,
        
        /// <remarks/>
        BARTHosted,
        
        /// <remarks/>
        CAMPS,
        
        /// <remarks/>
        RockwellCollins,
        
        /// <remarks/>
        Avianis,
        
        /// <remarks/>
        BeaconComm,
        
        /// <remarks/>
        DeltaPrivateJets,
        
        /// <remarks/>
        SkyService,
        
        /// <remarks/>
        JoinJet,
        
        /// <remarks/>
        PFM,
        
        /// <remarks/>
        AVMOSYS,
        
        /// <remarks/>
        LyonAviation,
        
        /// <remarks/>
        FOSPrivateHosting,
        
        /// <remarks/>
        GE,
        
        /// <remarks/>
        BoldIQ,
        
        /// <remarks/>
        FlightBridge,
        
        /// <remarks/>
        IPCFosGeneric,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class otherTax : BaseClass {
        
        private int requestIdField;
        
        private string taxDescField;
        
        private double taxGalField;
        
        private double taxAmtField;
        
        private double taxPcntField;
        
        private bool omitPPGField;
        
        private bool isCustomizableField;
        
        /// <remarks/>
        public int RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        public string TaxDesc {
            get {
                return this.taxDescField;
            }
            set {
                this.taxDescField = value;
            }
        }
        
        /// <remarks/>
        public double TaxGal {
            get {
                return this.taxGalField;
            }
            set {
                this.taxGalField = value;
            }
        }
        
        /// <remarks/>
        public double TaxAmt {
            get {
                return this.taxAmtField;
            }
            set {
                this.taxAmtField = value;
            }
        }
        
        /// <remarks/>
        public double TaxPcnt {
            get {
                return this.taxPcntField;
            }
            set {
                this.taxPcntField = value;
            }
        }
        
        /// <remarks/>
        public bool OmitPPG {
            get {
                return this.omitPPGField;
            }
            set {
                this.omitPPGField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCustomizable {
            get {
                return this.isCustomizableField;
            }
            set {
                this.isCustomizableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class otherFee : BaseClass {
        
        private int requestIdField;
        
        private string feeDescField;
        
        private double feeAmountField;
        
        private bool isStoredField;
        
        /// <remarks/>
        public int RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        public string FeeDesc {
            get {
                return this.feeDescField;
            }
            set {
                this.feeDescField = value;
            }
        }
        
        /// <remarks/>
        public double FeeAmount {
            get {
                return this.feeAmountField;
            }
            set {
                this.feeAmountField = value;
            }
        }
        
        /// <remarks/>
        public bool IsStored {
            get {
                return this.isStoredField;
            }
            set {
                this.isStoredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransactionFuelPrice : BaseClass {
        
        private int oIDField;
        
        private int requestIDField;
        
        private int fuelerIDField;
        
        private double minVolumeField;
        
        private double maxVolumeField;
        
        private double priceField;
        
        private string fBOField;
        
        private int fuelMasterIDField;
        
        private string iCAOField;
        
        /// <remarks/>
        public int OID {
            get {
                return this.oIDField;
            }
            set {
                this.oIDField = value;
            }
        }
        
        /// <remarks/>
        public int RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public int FuelerID {
            get {
                return this.fuelerIDField;
            }
            set {
                this.fuelerIDField = value;
            }
        }
        
        /// <remarks/>
        public double MinVolume {
            get {
                return this.minVolumeField;
            }
            set {
                this.minVolumeField = value;
            }
        }
        
        /// <remarks/>
        public double MaxVolume {
            get {
                return this.maxVolumeField;
            }
            set {
                this.maxVolumeField = value;
            }
        }
        
        /// <remarks/>
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string FBO {
            get {
                return this.fBOField;
            }
            set {
                this.fBOField = value;
            }
        }
        
        /// <remarks/>
        public int FuelMasterID {
            get {
                return this.fuelMasterIDField;
            }
            set {
                this.fuelMasterIDField = value;
            }
        }
        
        /// <remarks/>
        public string ICAO {
            get {
                return this.iCAOField;
            }
            set {
                this.iCAOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetTransactionCompletedEventHandler(object sender, GetTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DegaObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DegaObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateTransactionCompletedEventHandler(object sender, UpdateTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591