//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFM.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FuelManagementEntities : DbContext
    {
        public FuelManagementEntities()
            : base("name=FuelManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FuelOrderMessage> FuelOrderMessages { get; set; }
        public virtual DbSet<FuelOrderMessageAttachment> FuelOrderMessageAttachments { get; set; }
        public virtual DbSet<PartnerServiceIntegration> PartnerServiceIntegrations { get; set; }
        public virtual DbSet<LoginPermission> LoginPermissions { get; set; }
    }
}
