//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFM.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelOrderMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FuelOrderMessage()
        {
            this.FuelOrderMessageAttachments = new HashSet<FuelOrderMessageAttachment>();
        }
    
        public int Id { get; set; }
        public int UserID { get; set; }
        public int FuelOrderID { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuelOrderMessageAttachment> FuelOrderMessageAttachments { get; set; }
    }
}
