//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFM.EDM
{
    using System;
    
    public enum PermissionTypes : short
    {
        Edit = 1,
        ViewOnly = 2,
        Hide = 3
    }
}
