GO
/****** Object:  StoredProcedure [dbo].[up_InsertUpdate_FuelOrder]    Script Date: 2/10/2017 12:28:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


--region [dbo].[up_InsertUpdate_FuelOrder]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Marty using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[up_InsertUpdate_FuelOrder]
-- Date Generated: Monday, June 20, 2016
------------------------------------------------------------------------------------------------------------------------

ALTER PROCEDURE [dbo].[up_InsertUpdate_FuelOrder]
	@Id int,
	@AdminClientID int,
	@CustClientID int,
	@OrderedByUserID int,
	@AircraftID int,
	@TailNumber nvarchar(50) = '',
	@ICAO nchar(4),
	@FBO nvarchar(max),
	@DateRequested date,
	@AdminStatus smallint,
	@CustStatus smallint,
	@IsArchived bit,
	@IsDirectlyEntered bit,
	@QuotedPPG decimal(18, 5),
	@InvoicedPPG decimal(18, 5),
	@QuotedVolume decimal(18, 5),
	@InvoicedVolume decimal(18, 5),
	@FuelingDateTime datetime,
	@WholesaleQuoted float,
	@WholesaleInvoiced float,
	@InvoiceNumber varchar(50) = null,
	@BasePPG float,
	@NoFuel bit,
	@TripID int,
	@LegNumber int,
	@CertificateType nvarchar(50) = null,
	@FuelOn varchar(25) = null,
	@PostedRetail float = null,
	@RampFee float = null,
	@RampFeeWaivedAt float = null,
	@RequestedBy nvarchar(50) = null,
	@InvoiceStatus smallint = 0,
	@SupplierID int = null,
	@PlattsPrice decimal(18, 5) = null,
	@AdminNotes nvarchar(max) = null,
	@CustNotes nvarchar(max) = null,
	@Vendor nvarchar(max) = null,
	@Product nvarchar(150) = null,
	@Total decimal(18, 5) = null
AS

SET NOCOUNT ON

IF EXISTS(SELECT [Id] FROM [dbo].[FuelOrders] WHERE [Id] = @Id)
BEGIN
	UPDATE [dbo].[FuelOrders] SET
		[AdminClientID] = @AdminClientID,
		[CustClientID] = @CustClientID,
		[OrderedByUserID] = @OrderedByUserID,
		[AircraftID] = @AircraftID,
		[TailNumber] = @TailNumber,
		[ICAO] = @ICAO,
		[FBO] = @FBO,
		[DateRequested] = @DateRequested,
		[AdminStatus] = @AdminStatus,
		[CustStatus] = @CustStatus,
		[IsArchived] = @IsArchived,
		[IsDirectlyEntered] = @IsDirectlyEntered,
		[QuotedPPG] = @QuotedPPG,
		[InvoicedPPG] = @InvoicedPPG,
		[QuotedVolume] = @QuotedVolume,
		[InvoicedVolume] = @InvoicedVolume,
		[FuelingDateTime] = @FuelingDateTime,
		WholesaleQuoted = @WholesaleQuoted,
		WholesaleInvoiced = @WholesaleInvoiced,
		InvoiceNumber = @InvoiceNumber,
		BasePPG = @BasePPG,
		NoFuel = @NoFuel,
		TripID = @TripID,
		LegNumber = @LegNumber,
		CertificateType = @CertificateType,
		FuelOn = @FuelOn,
		PostedRetail = @PostedRetail,
		RampFee = @RampFee,
		RampFeeWaivedAt = @RampFeeWaivedAt,
		RequestedBy = @RequestedBy,
		InvoiceStatus = @InvoiceStatus,
		SupplierID = @SupplierID,
		PlattsPrice = @PlattsPrice,
		AdminNotes = @AdminNotes,
		CustNotes = @CustNotes,
		Vendor = @Vendor,
		Product = @Product,
		Total = @Total
	WHERE
		[Id] = @Id
END
ELSE
BEGIN
	INSERT INTO [dbo].[FuelOrders] (
		[AdminClientID],
		[CustClientID],
		[OrderedByUserID],
		[AircraftID],
		[TailNumber],
		[ICAO],
		[FBO],
		[DateRequested],
		[AdminStatus],
		[CustStatus],
		[IsArchived],
		[IsDirectlyEntered],
		[QuotedPPG],
		[InvoicedPPG],
		[QuotedVolume],
		[InvoicedVolume],
		[FuelingDateTime],
		WholesaleQuoted,
		WholesaleInvoiced,
		InvoiceNumber,
		BasePPG,
		NoFuel,
		TripID,
		LegNumber,
		CertificateType,
		FuelOn,
		PostedRetail,
		RampFee,
		RampFeeWaivedAt,
		RequestedBy,
		InvoiceStatus,
		SupplierID,
		PlattsPrice,
		AdminNotes,
		CustNotes,
		Vendor,
		Product,
		Total
	) VALUES (
		@AdminClientID,
		@CustClientID,
		@OrderedByUserID,
		@AircraftID,
		@TailNumber,
		@ICAO,
		@FBO,
		@DateRequested,
		@AdminStatus,
		@CustStatus,
		@IsArchived,
		@IsDirectlyEntered,
		@QuotedPPG,
		@InvoicedPPG,
		@QuotedVolume,
		@InvoicedVolume,
		@FuelingDateTime,
		@WholesaleQuoted,
		@WholesaleInvoiced,
		@InvoiceNumber,
		@BasePPG,
		@NoFuel,
		@TripID,
		@LegNumber,
		@CertificateType,
		@FuelOn,
		@PostedRetail,
		@RampFee,
		@RampFeeWaivedAt,
		@RequestedBy, 
		@InvoiceStatus,
		@SupplierID,
		@PlattsPrice,
		@AdminNotes,
		@CustNotes,
		@Vendor,
		@Product,
		@Total
	)
    SET @Id = @@IDENTITY
    
    --Insert associated supplier pricing records for a new fuel order
    insert into FuelOrderSupplierPricings (
      [Vendor]
      ,[IATA]
      ,[ICAO]
      ,[FBOName]
      ,[Min]
      ,[Max]
      ,[TotalWithTax]
      ,[Expires]
      ,[Product]
      ,[Notes]
      ,[AdminClientID]
      ,[SupplierID]
      ,[DateUploaded]
      ,[EffectiveDate]
      ,[FuelOrderId])
    select [Vendor]
      ,[IATA]
      ,[ICAO]
      ,[FBOName]
      ,[Min]
      ,[Max]
      ,[TotalWithTax]
      ,[Expires]
      ,[Product]
      ,[Notes]
      ,[AdminClientID]
      ,[SupplierID]
      ,[DateUploaded]
      ,[EffectiveDate]
      ,@Id
    from SupplierFuelsPrices sfp
    where AdminClientID = @AdminClientID
    and ICAO = @ICAO
    and (sfp.Expires IS NULL OR DATEADD(dd, 1, sfp.Expires) >= GETDATE())
					    AND (sfp.EffectiveDate is null or sfp.EffectiveDate <= GETDATE())
		                            AND 
		                            isnull(sfp.FBOName,'') not like '%lgr only%'
		                            AND (isnull(sfp.FBOName,'') NOT LIKE '%DC9%')
		                            AND (isnull(sfp.FBOName,'') NOT LIKE '%and larger%')
    
END


SELECT @Id AS Id 

GO
--endregion

